### PR TITLE
Form for creating meetrip

### LINKED ISSUE #3: 2-create-a-meetrip

### PR DESCRIPTION
**Pull request by prSathan**
closes #3

### CODE REVIEW

**Comment by marioribeiro** [comment]
The form is not doing anything at the moment. We need to create a POST request to the API to create Meetrips.

**Review by marioribeiro — CHANGES_REQUESTED** [review]
We need to create the Meetrip

**Review by KyeBracey — APPROVED** [review]
:shipit:

**Review by jjadeseravla — COMMENTED** [review]
:shipit:

**Review by jjadeseravla — APPROVED** [review]

**Pull request merged**
